In [55]:
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np
from matplotlib import pyplot as plt
import art#fully initialise module
from art.estimators.classification import SklearnClassifier
from art.estimators.classification.scikitlearn import ScikitlearnDecisionTreeClassifier
from art.attacks.evasion import DecisionTreeAttack
import warnings
warnings.filterwarnings('ignore')

In [56]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

data=pd.read_csv('dataset.csv')

# clean up column names

data.columns = data.columns.\
    str.strip().\
    str.lower()

#____remove non-numeric columns
    
data = data.select_dtypes(['number']) 


#__extracting dependent and independent variable

x=data.drop(['type'],axis=1)
y=data['type']
x=np.nan_to_num(x) #____replace nan with zero and inf with finite numbers

In [57]:
#______Splitting the data into Training and test dataset
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3,random_state=44)

In [58]:
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(n_estimators=100)
rfc.fit(x_train,y_train)

pred1=rfc.predict(x_test)

In [59]:
#accuracy for random forest
print('For Random Forest accuracy score is ',accuracy_score(y_test,pred1))
print('For Random Forest confusion_matrix is: \n\n',confusion_matrix(y_test,pred1))
print ('For Random Forest Classification Report: \n\n',classification_report(y_test,pred1))
false_positive_rate=confusion_matrix(y_test,pred1)[0][1]/(confusion_matrix(y_test,pred1)[0][0]+confusion_matrix(y_test,pred1)[0][1])
print("False Positive Rate: "+str(false_positive_rate))

For Random Forest accuracy score is  0.9579124579124579
For Random Forest confusion_matrix is: 

 [[506   8]
 [ 17  63]]
For Random Forest Classification Report: 

               precision    recall  f1-score   support

           0       0.97      0.98      0.98       514
           1       0.89      0.79      0.83        80

    accuracy                           0.96       594
   macro avg       0.93      0.89      0.91       594
weighted avg       0.96      0.96      0.96       594

False Positive Rate: 0.01556420233463035


In [60]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=0)
model.fit(X=x_train, y=y_train)

# Create ART classifier for scikit-learn GradientBoostingClassifier
art_classifier = ScikitlearnDecisionTreeClassifier(model=model)

# Create ART Zeroth Order Optimization attack
dta = DecisionTreeAttack(art_classifier)#art_classifier,offset=20.0)

# Generate adversarial samples with ART Zeroth Order Optimization attack
x_train_adv = dta.generate(x_train)

Decision tree attack: 100%|██████████████████████████████████████████████████████| 1187/1187 [00:00<00:00, 3090.99it/s]


In [61]:
x_train_adv

array([[4.9000000e+01, 8.4990000e+00, 3.2400000e+02, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [4.8000000e+01, 1.1000000e+01, 6.4000000e+02, ..., 3.4940000e+03,
        3.1000000e+01, 8.0000000e+00],
       [6.1000000e+01, 8.4990000e+00, 3.3425999e+04, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [6.0000000e+01, 1.1000000e+01, 0.0000000e+00, ..., 5.3920000e+03,
        3.5000000e+01, 7.0010000e+00],
       [4.6000000e+01, 9.0000000e+00, 0.0000000e+00, ..., 5.6400000e+02,
        6.0000000e+00, 7.0010000e+00],
       [7.5000000e+01, 1.6000000e+01, 0.0000000e+00, ..., 4.2470000e+03,
        4.1000000e+01, 6.9990000e+00]])

In [62]:
x_train

array([[4.9000e+01, 9.0000e+00, 3.2400e+02, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [4.8000e+01, 1.1000e+01, 6.4000e+02, ..., 3.4940e+03, 3.1000e+01,
        8.0000e+00],
       [6.1000e+01, 1.2000e+01, 3.9198e+04, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [6.0000e+01, 1.1000e+01, 0.0000e+00, ..., 5.3920e+03, 3.5000e+01,
        6.0000e+00],
       [4.6000e+01, 9.0000e+00, 0.0000e+00, ..., 5.6400e+02, 6.0000e+00,
        0.0000e+00],
       [7.5000e+01, 1.6000e+01, 0.0000e+00, ..., 4.2470e+03, 4.1000e+01,
        8.0000e+00]])

In [63]:
x_test_adv = dta.generate(x_test)

Decision tree attack: 100%|████████████████████████████████████████████████████████| 594/594 [00:00<00:00, 3070.16it/s]


In [64]:
x_test_adv

array([[5.1000e+01, 1.0000e+01, 0.0000e+00, ..., 5.0930e+03, 4.1000e+01,
        7.0010e+00],
       [5.6000e+01, 9.0000e+00, 0.0000e+00, ..., 2.4160e+03, 2.1000e+01,
        7.0010e+00],
       [1.2800e+02, 3.5001e+01, 2.9840e+04, ..., 4.3200e+02, 4.0000e+00,
        0.0000e+00],
       ...,
       [4.9000e+01, 9.0000e+00, 1.6200e+02, ..., 2.1380e+03, 2.5000e+01,
        7.0010e+00],
       [4.8000e+01, 1.0000e+01, 3.4500e+02, ..., 1.4740e+03, 1.9000e+01,
        7.0010e+00],
       [6.5000e+01, 1.1000e+01, 1.2339e+04, ..., 1.9220e+03, 2.2000e+01,
        7.0010e+00]])

In [65]:
x_test

array([[5.1000e+01, 1.0000e+01, 0.0000e+00, ..., 5.0930e+03, 4.1000e+01,
        6.0000e+00],
       [5.6000e+01, 9.0000e+00, 0.0000e+00, ..., 2.4160e+03, 2.1000e+01,
        6.0000e+00],
       [1.2800e+02, 2.5000e+01, 2.9840e+04, ..., 4.3200e+02, 4.0000e+00,
        0.0000e+00],
       ...,
       [4.9000e+01, 9.0000e+00, 1.6200e+02, ..., 2.1380e+03, 2.5000e+01,
        6.0000e+00],
       [4.8000e+01, 1.0000e+01, 3.4500e+02, ..., 1.4740e+03, 1.9000e+01,
        2.0000e+00],
       [6.5000e+01, 1.1000e+01, 1.2339e+04, ..., 1.9220e+03, 2.2000e+01,
        4.0000e+00]])

In [66]:
score = model.score(x_train, y_train)
print("Benign Training Score: %.4f" % score)

Benign Training Score: 1.0000


In [67]:
score = model.score(x_train_adv, y_train) #simply to see if they are matching or not
print("Adversarial Training Score: %.4f" % score)

Adversarial Training Score: 0.0000


In [68]:
score = model.score(x_test, y_test)
print("Benign Test Score: %.4f" % score)

Benign Test Score: 0.9327


In [69]:
score = model.score(x_test_adv, y_test) #not necessary
print("Adversarial Test Score: %.4f" % score)

Adversarial Test Score: 0.0673


In [81]:
#GradientBoostingClassifier #how model handles data when trained on adversarial data, does noise mess things up?
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(n_estimators=100)
rfc.fit(x_train_adv,y_train)

pred1=rfc.predict(x_test)

#accuracy for RandomForestClassifier
print('For RandomForestClassifier accuracy score is ',accuracy_score(y_test,pred1))
print('For RandomForestClassifier confusion_matrix is: \n\n',confusion_matrix(y_test,pred1))
print ('For RandomForestClassifier Classification Report: \n\n',classification_report(y_test,pred1))
false_positive_rate=confusion_matrix(y_test,pred1)[1][0]/(confusion_matrix(y_test,pred1)[1][0]+confusion_matrix(y_test,pred1)[1][1])
print("False Negative Rate: "+str(false_positive_rate))#actually false negative rate

For RandomForestClassifier accuracy score is  0.8956228956228957
For RandomForestClassifier confusion_matrix is: 

 [[486  28]
 [ 34  46]]
For RandomForestClassifier Classification Report: 

               precision    recall  f1-score   support

           0       0.93      0.95      0.94       514
           1       0.62      0.57      0.60        80

    accuracy                           0.90       594
   macro avg       0.78      0.76      0.77       594
weighted avg       0.89      0.90      0.89       594

False Negative Rate: 0.425


In [82]:
#GradientBoostingClassifier  #how model handles adversarial data, without adversarial training
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(n_estimators=100)
rfc.fit(x_train,y_train)

pred1=rfc.predict(x_test_adv)

#accuracy for RandomForestClassifier
print('For RandomForestClassifier accuracy score is ',accuracy_score(y_test,pred1))
print('For RandomForestClassifier confusion_matrix is: \n\n',confusion_matrix(y_test,pred1))
print ('For RandomForestClassifier Classification Report: \n\n',classification_report(y_test,pred1))
false_positive_rate=confusion_matrix(y_test,pred1)[1][0]/(confusion_matrix(y_test,pred1)[1][0]+confusion_matrix(y_test,pred1)[1][1])
print("False Negative Rate: "+str(false_positive_rate)) 

For RandomForestClassifier accuracy score is  0.9410774410774411
For RandomForestClassifier confusion_matrix is: 

 [[510   4]
 [ 31  49]]
For RandomForestClassifier Classification Report: 

               precision    recall  f1-score   support

           0       0.94      0.99      0.97       514
           1       0.92      0.61      0.74        80

    accuracy                           0.94       594
   macro avg       0.93      0.80      0.85       594
weighted avg       0.94      0.94      0.94       594

False Negative Rate: 0.3875


In [83]:
#GradientBoostingClassifier  #how model handles regular data, trained regularly
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(n_estimators=100)
rfc.fit(x_train,y_train)

pred1=rfc.predict(x_test)

#accuracy for RandomForestClassifier
print('For RandomForestClassifier accuracy score is ',accuracy_score(y_test,pred1))
print('For RandomForestClassifier confusion_matrix is: \n\n',confusion_matrix(y_test,pred1))
print ('For RandomForestClassifier Classification Report: \n\n',classification_report(y_test,pred1))
false_positive_rate=confusion_matrix(y_test,pred1)[1][0]/(confusion_matrix(y_test,pred1)[1][0]+confusion_matrix(y_test,pred1)[1][1])
print("False Negative Rate: "+str(false_positive_rate))

For RandomForestClassifier accuracy score is  0.9595959595959596
For RandomForestClassifier confusion_matrix is: 

 [[507   7]
 [ 17  63]]
For RandomForestClassifier Classification Report: 

               precision    recall  f1-score   support

           0       0.97      0.99      0.98       514
           1       0.90      0.79      0.84        80

    accuracy                           0.96       594
   macro avg       0.93      0.89      0.91       594
weighted avg       0.96      0.96      0.96       594

False Negative Rate: 0.2125


In [84]:
#GradientBoostingClassifier #correct final model, that is how it handles adversarial data, after adversarial training
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(n_estimators=100)
rfc.fit(x_train_adv,y_train)

pred1=rfc.predict(x_test_adv)

#accuracy for RandomForestClassifier
print('For RandomForestClassifier accuracy score is ',accuracy_score(y_test,pred1))
print('For RandomForestClassifier confusion_matrix is: \n\n',confusion_matrix(y_test,pred1))
print ('For RandomForestClassifier Classification Report: \n\n',classification_report(y_test,pred1))
false_positive_rate=confusion_matrix(y_test,pred1)[1][0]/(confusion_matrix(y_test,pred1)[1][0]+confusion_matrix(y_test,pred1)[1][1])
print("False Negative Rate: "+str(false_positive_rate))

For RandomForestClassifier accuracy score is  0.9427609427609428
For RandomForestClassifier confusion_matrix is: 

 [[495  19]
 [ 15  65]]
For RandomForestClassifier Classification Report: 

               precision    recall  f1-score   support

           0       0.97      0.96      0.97       514
           1       0.77      0.81      0.79        80

    accuracy                           0.94       594
   macro avg       0.87      0.89      0.88       594
weighted avg       0.94      0.94      0.94       594

False Negative Rate: 0.1875


In [85]:
model.predict(x_test_adv[0:1, :])[0]

1

In [75]:
model.predict(x_test[0:1, :])[0]

0