In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree

In [2]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [3]:
data=pd.read_csv('dataset.csv')

In [4]:
# to clean up the column names
data.columns = data.columns.\
    str.strip().\
    str.lower()


In [5]:
#this will remove non-numeric columns   
data = data.select_dtypes(['number']) 

In [6]:
#extracting dependent and independent variable
x=data.drop(['type'],axis=1)
y=data['type']
x=np.nan_to_num(x) #this replace nan with 0 & inf with finite numbers

In [7]:
#to split the data into training $=& test datasets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3,random_state=44)

In [8]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression

classifier=LogisticRegression(random_state=42)
classifier.fit(x_train,y_train)


E:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=42)

In [9]:
pred2 = classifier.predict(x_test)

In [10]:
#calc accuracy for logistic regression
print('For Logistic Regression accuracy score is ',accuracy_score(y_test,pred2))
print('For Logistic Regression confusion_matrix is: \n\n',confusion_matrix(y_test,pred2))
print ('For Logistic Regression Classification Report: \n\n',classification_report(y_test,pred2))


For Logistic Regression accuracy score is  0.8720538720538721
For Logistic Regression confusion_matrix is: 

 [[500  14]
 [ 62  18]]
For Logistic Regression Classification Report: 

               precision    recall  f1-score   support

           0       0.89      0.97      0.93       514
           1       0.56      0.23      0.32        80

    accuracy                           0.87       594
   macro avg       0.73      0.60      0.63       594
weighted avg       0.85      0.87      0.85       594



In [11]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

classifier2=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2) #multi/N-dimensional distance
classifier2.fit(x_train,y_train)

pred3=classifier2.predict(x_test)

In [12]:
#calc accuracy for KNN
print('For KNN accuracy score is ',accuracy_score(y_test,pred3))
print('For  KNN confusion_matrix is: \n\n',confusion_matrix(y_test,pred3))
print ('For  KNN Classification Report: \n\n',classification_report(y_test,pred3))

For KNN accuracy score is  0.9191919191919192
For  KNN confusion_matrix is: 

 [[497  17]
 [ 31  49]]
For  KNN Classification Report: 

               precision    recall  f1-score   support

           0       0.94      0.97      0.95       514
           1       0.74      0.61      0.67        80

    accuracy                           0.92       594
   macro avg       0.84      0.79      0.81       594
weighted avg       0.91      0.92      0.92       594



In [13]:
#Random forest
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(n_estimators=100)
rfc.fit(x_train,y_train)

pred1=rfc.predict(x_test)

#accuracy for random forest
print('For Random Forest accuracy score is ',accuracy_score(y_test,pred1))
print('For Random Forest confusion_matrix is: \n\n',confusion_matrix(y_test,pred1))
print ('For Random Forest Classification Report: \n\n',classification_report(y_test,pred1))


For Random Forest accuracy score is  0.9579124579124579
For Random Forest confusion_matrix is: 

 [[507   7]
 [ 18  62]]
For Random Forest Classification Report: 

               precision    recall  f1-score   support

           0       0.97      0.99      0.98       514
           1       0.90      0.78      0.83        80

    accuracy                           0.96       594
   macro avg       0.93      0.88      0.90       594
weighted avg       0.96      0.96      0.96       594



In [16]:
#Random forest
from sklearn.ensemble import GradientBoostingClassifier

rfc=GradientBoostingClassifier(n_estimators=100)
rfc.fit(x_train,y_train)

pred1=rfc.predict(x_test)

#accuracy for random forest
print('For GradientBoostingClassifier accuracy score is ',accuracy_score(y_test,pred1))
print('For GradientBoostingClassifier confusion_matrix is: \n\n',confusion_matrix(y_test,pred1))
print ('For GradientBoostingClassifier Classification Report: \n\n',classification_report(y_test,pred1))


For GradientBoostingClassifier accuracy score is  0.9511784511784511
For GradientBoostingClassifier confusion_matrix is: 

 [[503  11]
 [ 18  62]]
For GradientBoostingClassifier Classification Report: 

               precision    recall  f1-score   support

           0       0.97      0.98      0.97       514
           1       0.85      0.78      0.81        80

    accuracy                           0.95       594
   macro avg       0.91      0.88      0.89       594
weighted avg       0.95      0.95      0.95       594

